// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: api.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadSpendingFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSpendingFormRequest) Reset() {
	*x = LoadSpendingFormRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSpendingFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSpendingFormRequest) ProtoMessage() {}

func (x *LoadSpendingFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSpendingFormRequest.ProtoReflect.Descriptor instead.
func (*LoadSpendingFormRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type LoadSpendingFormResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Accounts      []*LoadSpendingFormResponse_Account   `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	SpendType     []*LoadSpendingFormResponse_SpendType `protobuf:"bytes,2,rep,name=spend_type,json=spendType,proto3" json:"spend_type,omitempty"`
	SpendTag      []*LoadSpendingFormResponse_SpendTag  `protobuf:"bytes,3,rep,name=spend_tag,json=spendTag,proto3" json:"spend_tag,omitempty"`
	Purpose       []*LoadSpendingFormResponse_Purpose   `protobuf:"bytes,4,rep,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSpendingFormResponse) Reset() {
	*x = LoadSpendingFormResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSpendingFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSpendingFormResponse) ProtoMessage() {}

func (x *LoadSpendingFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSpendingFormResponse.ProtoReflect.Descriptor instead.
func (*LoadSpendingFormResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoadSpendingFormResponse) GetAccounts() []*LoadSpendingFormResponse_Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *LoadSpendingFormResponse) GetSpendType() []*LoadSpendingFormResponse_SpendType {
	if x != nil {
		return x.SpendType
	}
	return nil
}

func (x *LoadSpendingFormResponse) GetSpendTag() []*LoadSpendingFormResponse_SpendTag {
	if x != nil {
		return x.SpendTag
	}
	return nil
}

func (x *LoadSpendingFormResponse) GetPurpose() []*LoadSpendingFormResponse_Purpose {
	if x != nil {
		return x.Purpose
	}
	return nil
}

type LoadIncomeFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadIncomeFormRequest) Reset() {
	*x = LoadIncomeFormRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadIncomeFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadIncomeFormRequest) ProtoMessage() {}

func (x *LoadIncomeFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadIncomeFormRequest.ProtoReflect.Descriptor instead.
func (*LoadIncomeFormRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

type LoadIncomeFormResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Accounts      []*LoadIncomeFormResponse_Account    `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	IncomeType    []*LoadIncomeFormResponse_IncomeType `protobuf:"bytes,2,rep,name=income_type,json=incomeType,proto3" json:"income_type,omitempty"`
	IncomeTag     []*LoadIncomeFormResponse_IncomeTag  `protobuf:"bytes,3,rep,name=income_tag,json=incomeTag,proto3" json:"income_tag,omitempty"`
	Purpose       []*LoadIncomeFormResponse_Purpose    `protobuf:"bytes,4,rep,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadIncomeFormResponse) Reset() {
	*x = LoadIncomeFormResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadIncomeFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadIncomeFormResponse) ProtoMessage() {}

func (x *LoadIncomeFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadIncomeFormResponse.ProtoReflect.Descriptor instead.
func (*LoadIncomeFormResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *LoadIncomeFormResponse) GetAccounts() []*LoadIncomeFormResponse_Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *LoadIncomeFormResponse) GetIncomeType() []*LoadIncomeFormResponse_IncomeType {
	if x != nil {
		return x.IncomeType
	}
	return nil
}

func (x *LoadIncomeFormResponse) GetIncomeTag() []*LoadIncomeFormResponse_IncomeTag {
	if x != nil {
		return x.IncomeTag
	}
	return nil
}

func (x *LoadIncomeFormResponse) GetPurpose() []*LoadIncomeFormResponse_Purpose {
	if x != nil {
		return x.Purpose
	}
	return nil
}

type LoadSpendingFormResponse_Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSpendingFormResponse_Account) Reset() {
	*x = LoadSpendingFormResponse_Account{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSpendingFormResponse_Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSpendingFormResponse_Account) ProtoMessage() {}

func (x *LoadSpendingFormResponse_Account) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSpendingFormResponse_Account.ProtoReflect.Descriptor instead.
func (*LoadSpendingFormResponse_Account) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *LoadSpendingFormResponse_Account) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadSpendingFormResponse_Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadSpendingFormResponse_SpendType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSpendingFormResponse_SpendType) Reset() {
	*x = LoadSpendingFormResponse_SpendType{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSpendingFormResponse_SpendType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSpendingFormResponse_SpendType) ProtoMessage() {}

func (x *LoadSpendingFormResponse_SpendType) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSpendingFormResponse_SpendType.ProtoReflect.Descriptor instead.
func (*LoadSpendingFormResponse_SpendType) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *LoadSpendingFormResponse_SpendType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadSpendingFormResponse_SpendType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadSpendingFormResponse_SpendTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSpendingFormResponse_SpendTag) Reset() {
	*x = LoadSpendingFormResponse_SpendTag{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSpendingFormResponse_SpendTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSpendingFormResponse_SpendTag) ProtoMessage() {}

func (x *LoadSpendingFormResponse_SpendTag) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSpendingFormResponse_SpendTag.ProtoReflect.Descriptor instead.
func (*LoadSpendingFormResponse_SpendTag) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 2}
}

func (x *LoadSpendingFormResponse_SpendTag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadSpendingFormResponse_SpendTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadSpendingFormResponse_Purpose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSpendingFormResponse_Purpose) Reset() {
	*x = LoadSpendingFormResponse_Purpose{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSpendingFormResponse_Purpose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSpendingFormResponse_Purpose) ProtoMessage() {}

func (x *LoadSpendingFormResponse_Purpose) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSpendingFormResponse_Purpose.ProtoReflect.Descriptor instead.
func (*LoadSpendingFormResponse_Purpose) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 3}
}

func (x *LoadSpendingFormResponse_Purpose) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadSpendingFormResponse_Purpose) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadIncomeFormResponse_Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadIncomeFormResponse_Account) Reset() {
	*x = LoadIncomeFormResponse_Account{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadIncomeFormResponse_Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadIncomeFormResponse_Account) ProtoMessage() {}

func (x *LoadIncomeFormResponse_Account) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadIncomeFormResponse_Account.ProtoReflect.Descriptor instead.
func (*LoadIncomeFormResponse_Account) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *LoadIncomeFormResponse_Account) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadIncomeFormResponse_Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadIncomeFormResponse_IncomeType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadIncomeFormResponse_IncomeType) Reset() {
	*x = LoadIncomeFormResponse_IncomeType{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadIncomeFormResponse_IncomeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadIncomeFormResponse_IncomeType) ProtoMessage() {}

func (x *LoadIncomeFormResponse_IncomeType) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadIncomeFormResponse_IncomeType.ProtoReflect.Descriptor instead.
func (*LoadIncomeFormResponse_IncomeType) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3, 1}
}

func (x *LoadIncomeFormResponse_IncomeType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadIncomeFormResponse_IncomeType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadIncomeFormResponse_IncomeTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadIncomeFormResponse_IncomeTag) Reset() {
	*x = LoadIncomeFormResponse_IncomeTag{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadIncomeFormResponse_IncomeTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadIncomeFormResponse_IncomeTag) ProtoMessage() {}

func (x *LoadIncomeFormResponse_IncomeTag) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadIncomeFormResponse_IncomeTag.ProtoReflect.Descriptor instead.
func (*LoadIncomeFormResponse_IncomeTag) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3, 2}
}

func (x *LoadIncomeFormResponse_IncomeTag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadIncomeFormResponse_IncomeTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadIncomeFormResponse_Purpose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadIncomeFormResponse_Purpose) Reset() {
	*x = LoadIncomeFormResponse_Purpose{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadIncomeFormResponse_Purpose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadIncomeFormResponse_Purpose) ProtoMessage() {}

func (x *LoadIncomeFormResponse_Purpose) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadIncomeFormResponse_Purpose.ProtoReflect.Descriptor instead.
func (*LoadIncomeFormResponse_Purpose) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3, 3}
}

func (x *LoadIncomeFormResponse_Purpose) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadIncomeFormResponse_Purpose) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\"\x19\n" +
	"\x17LoadSpendingFormRequest\"\xea\x03\n" +
	"\x18LoadSpendingFormResponse\x12A\n" +
	"\baccounts\x18\x01 \x03(\v2%.api.LoadSpendingFormResponse.AccountR\baccounts\x12F\n" +
	"\n" +
	"spend_type\x18\x02 \x03(\v2'.api.LoadSpendingFormResponse.SpendTypeR\tspendType\x12C\n" +
	"\tspend_tag\x18\x03 \x03(\v2&.api.LoadSpendingFormResponse.SpendTagR\bspendTag\x12?\n" +
	"\apurpose\x18\x04 \x03(\v2%.api.LoadSpendingFormResponse.PurposeR\apurpose\x1a-\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a/\n" +
	"\tSpendType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a.\n" +
	"\bSpendTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a-\n" +
	"\aPurpose\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x17\n" +
	"\x15LoadIncomeFormRequest\"\xe8\x03\n" +
	"\x16LoadIncomeFormResponse\x12?\n" +
	"\baccounts\x18\x01 \x03(\v2#.api.LoadIncomeFormResponse.AccountR\baccounts\x12G\n" +
	"\vincome_type\x18\x02 \x03(\v2&.api.LoadIncomeFormResponse.IncomeTypeR\n" +
	"incomeType\x12D\n" +
	"\n" +
	"income_tag\x18\x03 \x03(\v2%.api.LoadIncomeFormResponse.IncomeTagR\tincomeTag\x12=\n" +
	"\apurpose\x18\x04 \x03(\v2#.api.LoadIncomeFormResponse.PurposeR\apurpose\x1a-\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a0\n" +
	"\n" +
	"IncomeType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a/\n" +
	"\tIncomeTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a-\n" +
	"\aPurpose\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xea\x01\n" +
	"\aService\x12r\n" +
	"\x0fLoadSendingForm\x12\x1c.api.LoadSpendingFormRequest\x1a\x1d.api.LoadSpendingFormResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/load-spending-form\x12k\n" +
	"\x0eLoadIncomeForm\x12\x1a.api.LoadIncomeFormRequest\x1a\x1b.api.LoadIncomeFormResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/load-income-formB,Z*github.com/linhhuynhcoding/LinhFinance/apib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_goTypes = []any{
	(*LoadSpendingFormRequest)(nil),            // 0: api.LoadSpendingFormRequest
	(*LoadSpendingFormResponse)(nil),           // 1: api.LoadSpendingFormResponse
	(*LoadIncomeFormRequest)(nil),              // 2: api.LoadIncomeFormRequest
	(*LoadIncomeFormResponse)(nil),             // 3: api.LoadIncomeFormResponse
	(*LoadSpendingFormResponse_Account)(nil),   // 4: api.LoadSpendingFormResponse.Account
	(*LoadSpendingFormResponse_SpendType)(nil), // 5: api.LoadSpendingFormResponse.SpendType
	(*LoadSpendingFormResponse_SpendTag)(nil),  // 6: api.LoadSpendingFormResponse.SpendTag
	(*LoadSpendingFormResponse_Purpose)(nil),   // 7: api.LoadSpendingFormResponse.Purpose
	(*LoadIncomeFormResponse_Account)(nil),     // 8: api.LoadIncomeFormResponse.Account
	(*LoadIncomeFormResponse_IncomeType)(nil),  // 9: api.LoadIncomeFormResponse.IncomeType
	(*LoadIncomeFormResponse_IncomeTag)(nil),   // 10: api.LoadIncomeFormResponse.IncomeTag
	(*LoadIncomeFormResponse_Purpose)(nil),     // 11: api.LoadIncomeFormResponse.Purpose
}
var file_api_proto_depIdxs = []int32{
	4,  // 0: api.LoadSpendingFormResponse.accounts:type_name -> api.LoadSpendingFormResponse.Account
	5,  // 1: api.LoadSpendingFormResponse.spend_type:type_name -> api.LoadSpendingFormResponse.SpendType
	6,  // 2: api.LoadSpendingFormResponse.spend_tag:type_name -> api.LoadSpendingFormResponse.SpendTag
	7,  // 3: api.LoadSpendingFormResponse.purpose:type_name -> api.LoadSpendingFormResponse.Purpose
	8,  // 4: api.LoadIncomeFormResponse.accounts:type_name -> api.LoadIncomeFormResponse.Account
	9,  // 5: api.LoadIncomeFormResponse.income_type:type_name -> api.LoadIncomeFormResponse.IncomeType
	10, // 6: api.LoadIncomeFormResponse.income_tag:type_name -> api.LoadIncomeFormResponse.IncomeTag
	11, // 7: api.LoadIncomeFormResponse.purpose:type_name -> api.LoadIncomeFormResponse.Purpose
	0,  // 8: api.Service.LoadSendingForm:input_type -> api.LoadSpendingFormRequest
	2,  // 9: api.Service.LoadIncomeForm:input_type -> api.LoadIncomeFormRequest
	1,  // 10: api.Service.LoadSendingForm:output_type -> api.LoadSpendingFormResponse
	3,  // 11: api.Service.LoadIncomeForm:output_type -> api.LoadIncomeFormResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
