// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_LoadSendingForm_FullMethodName = "/api.Service/LoadSendingForm"
	Service_LoadIncomeForm_FullMethodName  = "/api.Service/LoadIncomeForm"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	LoadSendingForm(ctx context.Context, in *LoadSpendingFormRequest, opts ...grpc.CallOption) (*LoadSpendingFormResponse, error)
	LoadIncomeForm(ctx context.Context, in *LoadIncomeFormRequest, opts ...grpc.CallOption) (*LoadIncomeFormResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) LoadSendingForm(ctx context.Context, in *LoadSpendingFormRequest, opts ...grpc.CallOption) (*LoadSpendingFormResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadSpendingFormResponse)
	err := c.cc.Invoke(ctx, Service_LoadSendingForm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) LoadIncomeForm(ctx context.Context, in *LoadIncomeFormRequest, opts ...grpc.CallOption) (*LoadIncomeFormResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadIncomeFormResponse)
	err := c.cc.Invoke(ctx, Service_LoadIncomeForm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	LoadSendingForm(context.Context, *LoadSpendingFormRequest) (*LoadSpendingFormResponse, error)
	LoadIncomeForm(context.Context, *LoadIncomeFormRequest) (*LoadIncomeFormResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) LoadSendingForm(context.Context, *LoadSpendingFormRequest) (*LoadSpendingFormResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadSendingForm not implemented")
}
func (UnimplementedServiceServer) LoadIncomeForm(context.Context, *LoadIncomeFormRequest) (*LoadIncomeFormResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadIncomeForm not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call pancis, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_LoadSendingForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadSpendingFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).LoadSendingForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_LoadSendingForm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).LoadSendingForm(ctx, req.(*LoadSpendingFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_LoadIncomeForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadIncomeFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).LoadIncomeForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_LoadIncomeForm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).LoadIncomeForm(ctx, req.(*LoadIncomeFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadSendingForm",
			Handler:    _Service_LoadSendingForm_Handler,
		},
		{
			MethodName: "LoadIncomeForm",
			Handler:    _Service_LoadIncomeForm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
