// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Type      string           `json:"type"`
	Balance   pgtype.Int8      `json:"balance"`
	Currency  pgtype.Text      `json:"currency"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Income struct {
	ID        int64            `json:"id"`
	TypeID    int32            `json:"type_id"`
	Title     string           `json:"title"`
	Amount    int64            `json:"amount"`
	AccountID int64            `json:"account_id"`
	PurposeID pgtype.Int8      `json:"purpose_id"`
	Notes     pgtype.Text      `json:"notes"`
	Date      pgtype.Timestamp `json:"date"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type IncomeTag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type IncomeTagMap struct {
	IncomeID pgtype.Int8 `json:"income_id"`
	TagID    pgtype.Int8 `json:"tag_id"`
	Primary  interface{} `json:"primary"`
}

type IncomeType struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Purpose struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Spend struct {
	ID        int64            `json:"id"`
	TypeID    int32            `json:"type_id"`
	Title     string           `json:"title"`
	Amount    int64            `json:"amount"`
	AccountID int64            `json:"account_id"`
	PurposeID pgtype.Int8      `json:"purpose_id"`
	Notes     pgtype.Text      `json:"notes"`
	Date      pgtype.Timestamp `json:"date"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type SpendTag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type SpendTagMap struct {
	SpendID pgtype.Int8 `json:"spend_id"`
	TagID   pgtype.Int8 `json:"tag_id"`
	Primary interface{} `json:"primary"`
}

type SpendType struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Transfer struct {
	ID            int64            `json:"id"`
	FromAccountID int64            `json:"from_account_id"`
	ToAccountID   int64            `json:"to_account_id"`
	Amount        int64            `json:"amount"`
	Notes         pgtype.Text      `json:"notes"`
	Date          pgtype.Timestamp `json:"date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}
