// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTagToIncome(ctx context.Context, arg AddTagToIncomeParams) error
	AddTagToSpend(ctx context.Context, arg AddTagToSpendParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error)
	CreateIncomeTag(ctx context.Context, name string) (IncomeTag, error)
	CreateIncomeType(ctx context.Context, arg CreateIncomeTypeParams) (IncomeType, error)
	CreatePurpose(ctx context.Context, arg CreatePurposeParams) (Purpose, error)
	CreateSpend(ctx context.Context, arg CreateSpendParams) (Spend, error)
	CreateSpendTag(ctx context.Context, name string) (SpendTag, error)
	CreateSpendType(ctx context.Context, arg CreateSpendTypeParams) (SpendType, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteIncome(ctx context.Context, id int64) error
	DeleteIncomeTag(ctx context.Context, id int64) error
	DeleteIncomeType(ctx context.Context, id int32) error
	DeletePurpose(ctx context.Context, id int64) error
	DeleteSpend(ctx context.Context, id int64) error
	DeleteSpendTag(ctx context.Context, id int64) error
	DeleteSpendType(ctx context.Context, id int32) error
	DeleteTransfer(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetIncome(ctx context.Context, id int64) (Income, error)
	GetIncomeTag(ctx context.Context, id int64) (IncomeTag, error)
	GetIncomeType(ctx context.Context, id int32) (IncomeType, error)
	GetPurpose(ctx context.Context, id int64) (Purpose, error)
	GetSpend(ctx context.Context, id int64) (Spend, error)
	GetSpendTag(ctx context.Context, id int64) (SpendTag, error)
	GetSpendType(ctx context.Context, id int32) (SpendType, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListIncomeTags(ctx context.Context) ([]IncomeTag, error)
	ListIncomeTypes(ctx context.Context) ([]IncomeType, error)
	ListIncomes(ctx context.Context) ([]Income, error)
	ListPurposes(ctx context.Context) ([]Purpose, error)
	ListSpendTags(ctx context.Context) ([]SpendTag, error)
	ListSpendTypes(ctx context.Context) ([]SpendType, error)
	ListSpends(ctx context.Context) ([]Spend, error)
	ListTagsByIncome(ctx context.Context, incomeID pgtype.Int8) ([]IncomeTag, error)
	ListTagsBySpend(ctx context.Context, spendID pgtype.Int8) ([]SpendTag, error)
	ListTransfers(ctx context.Context) ([]Transfer, error)
	RemoveTagFromIncome(ctx context.Context, arg RemoveTagFromIncomeParams) error
	RemoveTagFromSpend(ctx context.Context, arg RemoveTagFromSpendParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error)
	UpdateIncomeType(ctx context.Context, arg UpdateIncomeTypeParams) (IncomeType, error)
	UpdatePurpose(ctx context.Context, arg UpdatePurposeParams) (Purpose, error)
	UpdateSpend(ctx context.Context, arg UpdateSpendParams) (Spend, error)
	UpdateSpendType(ctx context.Context, arg UpdateSpendTypeParams) (SpendType, error)
}

var _ Querier = (*Queries)(nil)
